### ISSUE TITLE
maintain image dimension with colorization

### ISSUE THREAD

**Issue by nhandali** [StanfordCS194/Team-6#12]
Can we get variable size image to work? Doesn't seem to be a simple fix when the dimensions aren't perfectly divisible by 4.

**Comment by chang100** [comment]
Can we just resize to a mod 4 == 0 size then do this?

**Comment by aleksanderdash** [comment]
Yeah, we can do a really simple resize through Pillow to just pad the dimensions with an extra couple pixels. Shouldn’t be a problem!

**Comment by chang100** [comment]
Ok I have fixed this. It is in the open pull request for commit 7932336e1943b013a2eb07a6db3925c1389e2ff3
